//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Realty = new HashSet<Realty>();
        }
    
        public int idAccount { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Admin { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PassportNumbers { get; set; }
        public string FIO { get; set; }
        public string email { get; set; }
        public Nullable<decimal> money { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realty> Realty { get; set; }
    }
}
