//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealtyEntities : DbContext
    {
        public RealtyEntities()
            : base("name=RealtyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeRealty> TypeRealty { get; set; }
        public virtual DbSet<StatusRealty> StatusRealty { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Realty> Realty { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
