//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int IdTransaction { get; set; }
        public Nullable<int> IdTransactionRealty { get; set; }
        public Nullable<int> TransactionAccountOwner { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> PriceTransaction { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdTransactionTypeRealty { get; set; }
        public Nullable<int> TransactionAccountBuyer { get; set; }
    
        public virtual Realty Realty { get; set; }
    }
}
